// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOFYLc8bCqT4RcFWvTGVyEnzoTWH6QBQ',
    appId: '1:807492998265:web:7422c90f1ee35a8d3a30a8',
    messagingSenderId: '807492998265',
    projectId: 'chat-app-d6e55',
    authDomain: 'chat-app-d6e55.firebaseapp.com',
    storageBucket: 'chat-app-d6e55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7iNS0O6IUtTwjKpZcbP5ORBj0EcfM2xE',
    appId: '1:807492998265:android:6c598f5e2e1bfa253a30a8',
    messagingSenderId: '807492998265',
    projectId: 'chat-app-d6e55',
    storageBucket: 'chat-app-d6e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8H0Gz7dhFm1GdGCJiBMQHX6Qtp7xPQ8',
    appId: '1:807492998265:ios:d04a4fe079ccc10d3a30a8',
    messagingSenderId: '807492998265',
    projectId: 'chat-app-d6e55',
    storageBucket: 'chat-app-d6e55.appspot.com',
    iosBundleId: 'com.example.futuraProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi8H0Gz7dhFm1GdGCJiBMQHX6Qtp7xPQ8',
    appId: '1:807492998265:ios:13c011ba676156083a30a8',
    messagingSenderId: '807492998265',
    projectId: 'chat-app-d6e55',
    storageBucket: 'chat-app-d6e55.appspot.com',
    iosBundleId: 'com.example.futuraProject.RunnerTests',
  );
}
